#!/usr/bin/env python3
"""Generate the Java runtime catalog from the reviewed RU translation JSON."""

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "localization" / "ru-strings.json"
DESTINATION = (
    ROOT
    / "APP/installCheck/app/src/main/java/com/install/appinstall/xl/ru/RuCatalog.java"
)
CHUNK_SIZE = 100


def java_quote(value):
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\b", "\\b")
        .replace("\f", "\\f")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )


def render(catalog):
    entries = sorted(catalog.items(), key=lambda item: (-len(item[0]), item[0]))
    chunks = [entries[index:index + CHUNK_SIZE] for index in range(0, len(entries), CHUNK_SIZE)]
    lines = [
        "// Generated by tools/generate_ru_catalog.py. Do not edit manually.",
        "package com.install.appinstall.xl.ru;",
        "",
        "import java.util.Collections;",
        "import java.util.LinkedHashMap;",
        "import java.util.Map;",
        "",
        "final class RuCatalog {",
        "    private RuCatalog() {}",
        "",
        "    static Map<String, String> create() {",
        "        Map<String, String> translations = new LinkedHashMap<>();",
    ]
    lines.extend(f"        add{index}(translations);" for index in range(len(chunks)))
    lines.extend(
        [
            "        return Collections.unmodifiableMap(translations);",
            "    }",
            "",
        ]
    )
    for index, chunk in enumerate(chunks):
        lines.append(f"    private static void add{index}(Map<String, String> translations) {{")
        for source, translation in chunk:
            lines.append(
                '        translations.put("{}", "{}");'.format(
                    java_quote(source), java_quote(translation)
                )
            )
        lines.extend(["    }", ""])
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    catalog = json.loads(SOURCE.read_text(encoding="utf-8"))
    output = render(catalog)
    if args.check:
        if not DESTINATION.is_file() or DESTINATION.read_text(encoding="utf-8") != output:
            print(f"Generated catalog is stale: {DESTINATION.relative_to(ROOT)}", file=sys.stderr)
            return 1
        return 0

    DESTINATION.parent.mkdir(parents=True, exist_ok=True)
    DESTINATION.write_text(output, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
